using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Collections.ObjectModel;

namespace Jib.WPF.Testbed
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
            LoadData();
        }
        private void LoadData()
        {
            ObservableCollection<Customer> list = new ObservableCollection<Customer>();
            list.Add(new Customer() { Address = "Obere Str. 57", City = "Berlin", CompanyName = "Alfreds Futterkiste", ContactName = "Maria Anders", ContactTitle = "Sales Representative", Country = "Germany", Phone = "030-0074321", PostalCode = "12209", Region = "", Amount = 698 });
            list.Add(new Customer() { Address = "Avda. de la Constitución 2222", City = "México D.F.", CompanyName = "Ana Trujillo Emparedados y helados", ContactName = "Ana Trujillo", ContactTitle = "Owner", Country = "Mexico", Phone = "(5) 555-4729", PostalCode = "05021", Region = "", Amount = 428 });
            list.Add(new Customer() { Address = "Mataderos 2312", City = "México D.F.", CompanyName = "Antonio Moreno Taquería", ContactName = "Antonio Moreno", ContactTitle = "Owner", Country = "Mexico", Phone = "(5) 555-3932", PostalCode = "05023", Region = "", Amount = 218 });
            list.Add(new Customer() { Address = "120 Hanover Sq.", City = "London", CompanyName = "Around the Horn", ContactName = "Thomas Hardy", ContactTitle = "Sales Representative", Country = "UK", Phone = "(171) 555-7788", PostalCode = "WA1 1DP", Region = "", Amount = 228 });
            list.Add(new Customer() { Address = "Berguvsvägen 8", City = "Luleå", CompanyName = "Berglunds snabbköp", ContactName = "Christina Berglund", ContactTitle = "Order Administrator", Country = "Sweden", Phone = "0921-12 34 65", PostalCode = "S-958 22", Region = "", Amount = 917 });
            list.Add(new Customer() { Address = "Forsterstr. 57", City = "Mannheim", CompanyName = "Blauer See Delikatessen", ContactName = "Hanna Moos", ContactTitle = "Sales Representative", Country = "Germany", Phone = "0621-08460", PostalCode = "68306", Region = "", Amount = 726 });
            list.Add(new Customer() { Address = "24, place Kléber", City = "Strasbourg", CompanyName = "Blondesddsl père et fils", ContactName = "Frédérique Citeaux", ContactTitle = "Marketing Manager", Country = "France", Phone = "88.60.15.31", PostalCode = "67000", Region = "", Amount = 935 });
            list.Add(new Customer() { Address = "C/ Araquil, 67", City = "Madrid", CompanyName = "Bólido Comidas preparadas", ContactName = "Martín Sommer", ContactTitle = "Owner", Country = "Spain", Phone = "(91) 555 22 82", PostalCode = "28023", Region = "", Amount = 536 });
            list.Add(new Customer() { Address = "12, rue des Bouchers", City = "Marseille", CompanyName = "Bon app'", ContactName = "Laurence Lebihan", ContactTitle = "Owner", Country = "France", Phone = "91.24.45.40", PostalCode = "13008", Region = "", Amount = 331 });
            list.Add(new Customer() { Address = "23 Tsawassen Blvd.", City = "Tsawassen", CompanyName = "Bottom-Dollar Markets", ContactName = "Elizabeth Lincoln", ContactTitle = "Accounting Manager", Country = "Canada", Phone = "(604) 555-4729", PostalCode = "T2F 8M4", Region = "BC", Amount = 323 });
            list.Add(new Customer() { Address = "Fauntleroy Circus", City = "London", CompanyName = "B's Beverages", ContactName = "Victoria Ashworth", ContactTitle = "Sales Representative", Country = "UK", Phone = "(171) 555-1212", PostalCode = "EC2 5NT", Region = "", Amount = 47 });
            list.Add(new Customer() { Address = "Cerrito 333", City = "Buenos Aires", CompanyName = "Cactus Comidas para llevar", ContactName = "Patricio Simpson", ContactTitle = "Sales Agent", Country = "Argentina", Phone = "(1) 135-5555", PostalCode = "1010", Region = "", Amount = 543 });
            list.Add(new Customer() { Address = "Sierras de Granada 9993", City = "México D.F.", CompanyName = "Centro comercial Moctezuma", ContactName = "Francisco Chang", ContactTitle = "Marketing Manager", Country = "Mexico", Phone = "(5) 555-3392", PostalCode = "05022", Region = "", Amount = 655 });
            list.Add(new Customer() { Address = "Hauptstr. 29", City = "Bern", CompanyName = "Chop-suey Chinese", ContactName = "Yang Wang", ContactTitle = "Owner", Country = "Switzerland", Phone = "0452-076545", PostalCode = "3012", Region = "", Amount = 983 });
            list.Add(new Customer() { Address = "Av. dos Lusíadas, 23", City = "Sao Paulo", CompanyName = "Comércio Mineiro", ContactName = "Pedro Afonso", ContactTitle = "Sales Associate", Country = "Brazil", Phone = "(11) 555-7647", PostalCode = "05432-043", Region = "SP", Amount = 821 });
            list.Add(new Customer() { Address = "Berkeley Gardens 12 Brewery", City = "London", CompanyName = "Consolidated Holdings", ContactName = "Elizabeth Brown", ContactTitle = "Sales Representative", Country = "UK", Phone = "(171) 555-2282", PostalCode = "WX1 6LT", Region = "", Amount = 719 });
            list.Add(new Customer() { Address = "Walserweg 21", City = "Aachen", CompanyName = "Drachenblut Delikatessen", ContactName = "Sven Ottlieb", ContactTitle = "Order Administrator", Country = "Germany", Phone = "0241-039123", PostalCode = "52066", Region = "", Amount = 721 });
            list.Add(new Customer() { Address = "67, rue des Cinquante Otages", City = "Nantes", CompanyName = "Du monde entier", ContactName = "Janine Labrune", ContactTitle = "Owner", Country = "France", Phone = "40.67.88.88", PostalCode = "44000", Region = "", Amount = 907 });
            list.Add(new Customer() { Address = "35 King George", City = "London", CompanyName = "Eastern Connection", ContactName = "Ann Devon", ContactTitle = "Sales Agent", Country = "UK", Phone = "(171) 555-0297", PostalCode = "WX3 6FW", Region = "", Amount = 591 });
            list.Add(new Customer() { Address = "Kirchgasse 6", City = "Graz", CompanyName = "Ernst Handel", ContactName = "Roland Mendel", ContactTitle = "Sales Manager", Country = "Austria", Phone = "7675-3425", PostalCode = "8010", Region = "", Amount = 456 });
            list.Add(new Customer() { Address = "Rua Orós, 92", City = "Sao Paulo", CompanyName = "Familia Arquibaldo", ContactName = "Aria Cruz", ContactTitle = "Marketing Assistant", Country = "Brazil", Phone = "(11) 555-9857", PostalCode = "05442-030", Region = "SP", Amount = 58 });
            list.Add(new Customer() { Address = "C/ Moralzarzal, 86", City = "Madrid", CompanyName = "FISSA Fabrica Inter. Salchichas S.A.", ContactName = "Diego Roel", ContactTitle = "Accounting Manager", Country = "Spain", Phone = "(91) 555 94 44", PostalCode = "28034", Region = "", Amount = 51 });
            list.Add(new Customer() { Address = "184, chaussée de Tournai", City = "Lille", CompanyName = "Folies gourmandes", ContactName = "Martine Rancé", ContactTitle = "Assistant Sales Agent", Country = "France", Phone = "20.16.10.16", PostalCode = "59000", Region = "", Amount = 45 });
            list.Add(new Customer() { Address = "Åkergatan 24", City = "Bräcke", CompanyName = "Folk och fä HB", ContactName = "Maria Larsson", ContactTitle = "Owner", Country = "Sweden", Phone = "0695-34 67 21", PostalCode = "S-844 67", Region = "", Amount = 920 });
            list.Add(new Customer() { Address = "Berliner Platz 43", City = "München", CompanyName = "Frankenversand", ContactName = "Peter Franken", ContactTitle = "Marketing Manager", Country = "Germany", Phone = "089-0877310", PostalCode = "80805", Region = "", Amount = 776 });
            list.Add(new Customer() { Address = "54, rue Royale", City = "Nantes", CompanyName = "France restauration", ContactName = "Carine Schmitt", ContactTitle = "Marketing Manager", Country = "France", Phone = "40.32.21.21", PostalCode = "44000", Region = "", Amount = 364 });
            list.Add(new Customer() { Address = "Via Monte Bianco 34", City = "Torino", CompanyName = "Franchi S.p.A.", ContactName = "Paolo Accorti", ContactTitle = "Sales Representative", Country = "Italy", Phone = "011-4988260", PostalCode = "10100", Region = "", Amount = 769 });
            list.Add(new Customer() { Address = "Jardim das rosas n. 32", City = "Lisboa", CompanyName = "Furia Bacalhau e Frutos do Mar", ContactName = "Lino Rodriguez", ContactTitle = "Sales Manager", Country = "Portugal", Phone = "(1) 354-2534", PostalCode = "1675", Region = "", Amount = 718 });
            list.Add(new Customer() { Address = "Rambla de Cataluña, 23", City = "Barcelona", CompanyName = "Galería del gastrónomo", ContactName = "Eduardo Saavedra", ContactTitle = "Marketing Manager", Country = "Spain", Phone = "(93) 203 4560", PostalCode = "08022", Region = "", Amount = 885 });
            list.Add(new Customer() { Address = "C/ Romero, 33", City = "Sevilla", CompanyName = "Godos Cocina Típica", ContactName = "José Pedro Freyre", ContactTitle = "Sales Manager", Country = "Spain", Phone = "(95) 555 82 82", PostalCode = "41101", Region = "", Amount = 730 });
            list.Add(new Customer() { Address = "Av. Brasil, 442", City = "Campinas", CompanyName = "Gourmet Lanchonetes", ContactName = "André Fonseca", ContactTitle = "Sales Associate", Country = "Brazil", Phone = "(11) 555-9482", PostalCode = "04876-786", Region = "SP", Amount = 409 });
            list.Add(new Customer() { Address = "2732 Baker Blvd.", City = "Eugene", CompanyName = "Great Lakes Food Market", ContactName = "Howard Snyder", ContactTitle = "Marketing Manager", Country = "USA", Phone = "(503) 555-7555", PostalCode = "97403", Region = "OR", Amount = 730 });
            list.Add(new Customer() { Address = "5ª Ave. Los Palos Grandes", City = "Caracas", CompanyName = "GROSELLA-Restaurante", ContactName = "Manuel Pereira", ContactTitle = "Owner", Country = "Venezuela", Phone = "(2) 283-2951", PostalCode = "1081", Region = "DF", Amount = 899 });
            list.Add(new Customer() { Address = "Rua do Paço, 67", City = "Rio de Janeiro", CompanyName = "Hanari Carnes", ContactName = "Mario Pontes", ContactTitle = "Accounting Manager", Country = "Brazil", Phone = "(21) 555-0091", PostalCode = "05454-876", Region = "RJ", Amount = 727 });
            list.Add(new Customer() { Address = "Carrera 22 con Ave. Carlos Soublette #8-35", City = "San Cristóbal", CompanyName = "HILARION-Abastos", ContactName = "Carlos Hernández", ContactTitle = "Sales Representative", Country = "Venezuela", Phone = "(5) 555-1340", PostalCode = "5022", Region = "Táchira", Amount = 395 });
            list.Add(new Customer() { Address = "City Center Plaza 516 Main St.", City = "Elgin", CompanyName = "Hungry Coyote Import Store", ContactName = "Yoshi Latimer", ContactTitle = "Sales Representative", Country = "USA", Phone = "(503) 555-6874", PostalCode = "97827", Region = "OR", Amount = 287 });
            list.Add(new Customer() { Address = "8 Johnstown Road", City = "Cork", CompanyName = "Hungry Owl All-Night Grocers", ContactName = "Patricia McKenna", ContactTitle = "Sales Associate", Country = "Ireland", Phone = "2967 542", PostalCode = "", Region = "Co. Cork", Amount = 732 });
            list.Add(new Customer() { Address = "Garden House Crowther Way", City = "Cowes", CompanyName = "Island Trading", ContactName = "Helen Bennett", ContactTitle = "Marketing Manager", Country = "UK", Phone = "(198) 555-8888", PostalCode = "PO31 7PJ", Region = "Isle of Wight", Amount = 248 });
            list.Add(new Customer() { Address = "Maubelstr. 90", City = "Brandenburg", CompanyName = "Königlich Essen", ContactName = "Philip Cramer", ContactTitle = "Sales Associate", Country = "Germany", Phone = "0555-09876", PostalCode = "14776", Region = "", Amount = 71 });
            list.Add(new Customer() { Address = "67, avenue de l'Europe", City = "Versailles", CompanyName = "La corne d'abondance", ContactName = "Daniel Tonini", ContactTitle = "Sales Representative", Country = "France", Phone = "30.59.84.10", PostalCode = "78000", Region = "", Amount = 140 });
            list.Add(new Customer() { Address = "1 rue Alsace-Lorraine", City = "Toulouse", CompanyName = "La maison d'Asie", ContactName = "Annette Roulet", ContactTitle = "Sales Manager", Country = "France", Phone = "61.77.61.10", PostalCode = "31000", Region = "", Amount = 278 });
            list.Add(new Customer() { Address = "1900 Oak St.", City = "Vancouver", CompanyName = "Laughing Bacchus Wine Cellars", ContactName = "Yoshi Tannamuri", ContactTitle = "Marketing Assistant", Country = "Canada", Phone = "(604) 555-3392", PostalCode = "V3F 2K1", Region = "BC", Amount = 935 });
            list.Add(new Customer() { Address = "12 Orchestra Terrace", City = "Walla Walla", CompanyName = "Lazy K Kountry Store", ContactName = "John Steel", ContactTitle = "Marketing Manager", Country = "USA", Phone = "(509) 555-7969", PostalCode = "99362", Region = "WA", Amount = 443 });
            list.Add(new Customer() { Address = "Magazinweg 7", City = "Frankfurt a.M.", CompanyName = "Lehmanns Marktstand", ContactName = "Renate Messner", ContactTitle = "Sales Representative", Country = "Germany", Phone = "069-0245984", PostalCode = "60528", Region = "", Amount = 721 });
            list.Add(new Customer() { Address = "87 Polk St. Suite 5", City = "San Francisco", CompanyName = "Let's Stop N Shop", ContactName = "Jaime Yorres", ContactTitle = "Owner", Country = "USA", Phone = "(415) 555-5938", PostalCode = "94117", Region = "CA", Amount = 239 });
            list.Add(new Customer() { Address = "Carrera 52 con Ave. Bolívar #65-98 Llano Largo", City = "Barquisimeto", CompanyName = "LILA-Supermercado", ContactName = "Carlos González", ContactTitle = "Accounting Manager", Country = "Venezuela", Phone = "(9) 331-6954", PostalCode = "3508", Region = "Lara", Amount = 621 });
            list.Add(new Customer() { Address = "Ave. 5 de Mayo Porlamar", City = "I. de Margarita", CompanyName = "LINO-Delicateses", ContactName = "Felipe Izquierdo", ContactTitle = "Owner", Country = "Venezuela", Phone = "(8) 34-56-12", PostalCode = "4980", Region = "Nueva Esparta", Amount = 589 });
            list.Add(new Customer() { Address = "89 Chiaroscuro Rd.", City = "Portland", CompanyName = "Lonesome Pine Restaurant", ContactName = "Fran Wilson", ContactTitle = "Sales Manager", Country = "USA", Phone = "(503) 555-9573", PostalCode = "97219", Region = "OR", Amount = 919 });
            list.Add(new Customer() { Address = "Via Ludovico il Moro 22", City = "Bergamo", CompanyName = "Magazzini Alimentari Riuniti", ContactName = "Giovanni Rovelli", ContactTitle = "Marketing Manager", Country = "Italy", Phone = "035-640230", PostalCode = "24100", Region = "", Amount = 477 });
            list.Add(new Customer() { Address = "Rue Joseph-Bens 532", City = "Bruxelles", CompanyName = "Maison Dewey", ContactName = "Catherine Dewey", ContactTitle = "Sales Agent", Country = "Belgium", Phone = "(02) 201 24 67", PostalCode = "B-1180", Region = "", Amount = 40 });
            list.Add(new Customer() { Address = "43 rue St. Laurent", City = "Montréal", CompanyName = "Mère Paillarde", ContactName = "Jean Fresnière", ContactTitle = "Marketing Assistant", Country = "Canada", Phone = "(514) 555-8054", PostalCode = "H1J 1C3", Region = "Québec", Amount = 448 });
            list.Add(new Customer() { Address = "Heerstr. 22", City = "Leipzig", CompanyName = "Morgenstern Gesundkost", ContactName = "Alexander Feuer", ContactTitle = "Marketing Assistant", Country = "Germany", Phone = "0342-023176", PostalCode = "04179", Region = "", Amount = 10 });
            list.Add(new Customer() { Address = "South House 300 Queensbridge", City = "London", CompanyName = "North/South", ContactName = "Simon Crowther", ContactTitle = "Sales Associate", Country = "UK", Phone = "(171) 555-7733", PostalCode = "SW7 1RZ", Region = "", Amount = 13 });
            list.Add(new Customer() { Address = "Ing. Gustavo Moncada 8585 Piso 20-A", City = "Buenos Aires", CompanyName = "Océano Atlántico Ltda.", ContactName = "Yvonne Moncada", ContactTitle = "Sales Agent", Country = "Argentina", Phone = "(1) 135-5333", PostalCode = "1010", Region = "", Amount = 527 });
            list.Add(new Customer() { Address = "2743 Bering St.", City = "Anchorage", CompanyName = "Old World Delicatessen", ContactName = "Rene Phillips", ContactTitle = "Sales Representative", Country = "USA", Phone = "(907) 555-7584", PostalCode = "99508", Region = "AK", Amount = 331 });
            list.Add(new Customer() { Address = "Mehrheimerstr. 369", City = "Köln", CompanyName = "Ottilies Käseladen", ContactName = "Henriette Pfalzheim", ContactTitle = "Owner", Country = "Germany", Phone = "0221-0644327", PostalCode = "50739", Region = "", Amount = 647 });
            list.Add(new Customer() { Address = "265, boulevard Charonne", City = "Paris", CompanyName = "Paris spécialités", ContactName = "Marie Bertrand", ContactTitle = "Owner", Country = "France", Phone = "(1) 42.34.22.66", PostalCode = "75012", Region = "", Amount = 384 });
            list.Add(new Customer() { Address = "Calle Dr. Jorge Cash 321", City = "México D.F.", CompanyName = "Pericles Comidas clásicas", ContactName = "Guillermo Fernández", ContactTitle = "Sales Representative", Country = "Mexico", Phone = "(5) 552-3745", PostalCode = "05033", Region = "", Amount = 284 });
            list.Add(new Customer() { Address = "Geislweg 14", City = "Salzburg", CompanyName = "Piccolo und mehr", ContactName = "Georg Pipps", ContactTitle = "Sales Manager", Country = "Austria", Phone = "6562-9722", PostalCode = "5020", Region = "", Amount = 439 });
            list.Add(new Customer() { Address = "Estrada da saúde n. 58", City = "Lisboa", CompanyName = "Princesa Isabel Vinhos", ContactName = "Isabel de Castro", ContactTitle = "Sales Representative", Country = "Portugal", Phone = "(1) 356-5634", PostalCode = "1756", Region = "", Amount = 554 });
            list.Add(new Customer() { Address = "Rua da Panificadora, 12", City = "Rio de Janeiro", CompanyName = "Que Delícia", ContactName = "Bernardo Batista", ContactTitle = "Accounting Manager", Country = "Brazil", Phone = "(21) 555-4252", PostalCode = "02389-673", Region = "RJ", Amount = 943 });
            list.Add(new Customer() { Address = "Alameda dos Canàrios, 891", City = "Sao Paulo", CompanyName = "Queen Cozinha", ContactName = "Lúcia Carvalho", ContactTitle = "Marketing Assistant", Country = "Brazil", Phone = "(11) 555-1189", PostalCode = "05487-020", Region = "SP", Amount = 218 });
            list.Add(new Customer() { Address = "Taucherstraße 10", City = "Cunewalde", CompanyName = "QUICK-Stop", ContactName = "Horst Kloss", ContactTitle = "Accounting Manager", Country = "Germany", Phone = "0372-035188", PostalCode = "01307", Region = "", Amount = 638 });
            list.Add(new Customer() { Address = "Av. del Libertador 900", City = "Buenos Aires", CompanyName = "Rancho grande", ContactName = "Sergio Gutiérrez", ContactTitle = "Sales Representative", Country = "Argentina", Phone = "(1) 123-5555", PostalCode = "1010", Region = "", Amount = 588 });
            list.Add(new Customer() { Address = "2817 Milton Dr.", City = "Albuquerque", CompanyName = "Rattlesnake Canyon Grocery", ContactName = "Paula Wilson", ContactTitle = "Assistant Sales Representative", Country = "USA", Phone = "(505) 555-5939", PostalCode = "87110", Region = "NM", Amount = 901 });
            list.Add(new Customer() { Address = "Strada Provinciale 124", City = "Reggio Emilia", CompanyName = "Reggiani Caseifici", ContactName = "Maurizio Moroni", ContactTitle = "Sales Associate", Country = "Italy", Phone = "0522-556721", PostalCode = "42100", Region = "", Amount = 303, IsActive = false });
            list.Add(new Customer() { Address = "Av. Copacabana, 267", City = "Rio de Janeiro", CompanyName = "Ricardo Adocicados", ContactName = "Janete Limeira", ContactTitle = "Assistant Sales Agent", Country = "Brazil", Phone = "(21) 555-3412", PostalCode = "02389-890", Region = "RJ", Amount = 630 });
            list.Add(new Customer() { Address = "Grenzacherweg 237", City = "Genève", CompanyName = "Richter Supermarkt", ContactName = "Michael Holz", ContactTitle = "Sales Manager", Country = "Switzerland", Phone = "0897-034214", PostalCode = "1203", Region = "", Amount = 914 });
            list.Add(new Customer() { Address = "Gran Vía, 1", City = "Madrid", CompanyName = "Romero y tomillo", ContactName = "Alejandra Camino", ContactTitle = "Accounting Manager", Country = "Spain", Phone = "(91) 745 6200", PostalCode = "28001", Region = "", Amount = 589 });
            list.Add(new Customer() { Address = "Erling Skakkes gate 78", City = "Stavern", CompanyName = "Santé Gourmet", ContactName = "Jonas Bergulfsen", ContactTitle = "Owner", Country = "Norway", Phone = "07-98 92 35", PostalCode = "4110", Region = "", Amount = 535, IsActive = false });
            list.Add(new Customer() { Address = "187 Suffolk Ln.", City = "Boise", CompanyName = "Save-a-lot Markets", ContactName = "Jose Pavarotti", ContactTitle = "Sales Representative", Country = "USA", Phone = "(208) 555-8097", PostalCode = "83720", Region = "ID", Amount = 974 });
            list.Add(new Customer() { Address = "90 Wadhurst Rd.", City = "London", CompanyName = "Seven Seas Imports", ContactName = "Hari Kumar", ContactTitle = "Sales Manager", Country = "UK", Phone = "(171) 555-1717", PostalCode = "OX15 4NB", Region = "", Amount = 473 });
            list.Add(new Customer() { Address = "Vinbæltet 34", City = "Kobenhavn", CompanyName = "Simons bistro", ContactName = "Jytte Petersen", ContactTitle = "Owner", Country = "Denmark", Phone = "31 12 34 56", PostalCode = "1734", Region = "", Amount = 837 });
            list.Add(new Customer() { Address = "25, rue Lauriston", City = "Paris", CompanyName = "Spécialités du monde", ContactName = "Dominique Perrier", ContactTitle = "Marketing Manager", Country = "France", Phone = "(1) 47.55.60.10", PostalCode = "75016", Region = "", Amount = 451 });
            list.Add(new Customer() { Address = "P.O. Box 555", City = "Lander", CompanyName = "Split Rail Beer & Ale", ContactName = "Art Braunschweiger", ContactTitle = "Sales Manager", Country = "USA", Phone = "(307) 555-4680", PostalCode = "82520", Region = "WY", Amount = 179 });
            list.Add(new Customer() { Address = "Boulevard Tirou, 255", City = "Charleroi", CompanyName = "Suprêmes délices", ContactName = "Pascale Cartrain", ContactTitle = "Accounting Manager", Country = "Belgium", Phone = "(071) 23 67 22 20", PostalCode = "B-6000", Region = "", Amount = 110 });
            list.Add(new Customer() { Address = "89 Jefferson Way Suite 2", City = "Portland", CompanyName = "The Big Cheese", ContactName = "Liz Nixon", ContactTitle = "Marketing Manager", Country = "USA", Phone = "(503) 555-3612", PostalCode = "97201", Region = "OR", Amount = 595 });
            list.Add(new Customer() { Address = "55 Grizzly Peak Rd.", City = "Butte", CompanyName = "The Cracker Box", ContactName = "Liu Wong", ContactTitle = "Marketing Assistant", Country = "USA", Phone = "(406) 555-5834", PostalCode = "59801", Region = "MT", Amount = 310 });
            list.Add(new Customer() { Address = "Luisenstr. 48", City = "Münster", CompanyName = "Toms Spezialitäten", ContactName = "Karin Josephs", ContactTitle = "Marketing Manager", Country = "Germany", Phone = "0251-031259", PostalCode = "44087", Region = "", Amount = 681 });
            list.Add(new Customer() { Address = "Avda. Azteca 123", City = "México D.F.", CompanyName = "Tortuga Restaurante", ContactName = "Miguel Angel Paolino", ContactTitle = "Owner", Country = "Mexico", Phone = "(5) 555-2933", PostalCode = "05033", Region = "", Amount = 156 });
            list.Add(new Customer() { Address = "Av. Inês de Castro, 414", City = "Sao Paulo", CompanyName = "Tradição Hipermercados", ContactName = "Anabela Domingues", ContactTitle = "Sales Representative", Country = "Brazil", Phone = "(11) 555-2167", PostalCode = "05634-030", Region = "SP", Amount = 761 });
            list.Add(new Customer() { Address = "722 DaVinci Blvd.", City = "Kirkland", CompanyName = "Trail's Head Gourmet Provisioners", ContactName = "Helvetius Nagy", ContactTitle = "Sales Associate", Country = "USA", Phone = "(206) 555-8257", PostalCode = "98034", Region = "WA", Amount = 837 });
            list.Add(new Customer() { Address = "Smagsloget 45", City = "Århus", CompanyName = "Vaffeljernet", ContactName = "Palle Ibsen", ContactTitle = "Sales Manager", Country = "Denmark", Phone = "86 21 32 43", PostalCode = "8200", Region = "", Amount = 242 });
            list.Add(new Customer() { Address = "2, rue du Commerce", City = "Lyon", CompanyName = "Victuailles en stock", ContactName = "Mary Saveley", ContactTitle = "Sales Agent", Country = "France", Phone = "78.32.54.86", PostalCode = "69004", Region = "", Amount = 845 });
            list.Add(new Customer() { Address = "59 rue de l'Abbaye", City = "Reims", CompanyName = "Vins et alcools Chevalier", ContactName = "Paul Henriot", ContactTitle = "Accounting Manager", Country = "France", Phone = "26.47.15.10", PostalCode = "51100", Region = "", Amount = 282 });
            list.Add(new Customer() { Address = "Adenauerallee 900", City = "Stuttgart", CompanyName = "Die Wandernde Kuh", ContactName = "Rita Müller", ContactTitle = "Sales Representative", Country = "Germany", Phone = "0711-020361", PostalCode = "70563", Region = "", Amount = 399 });
            list.Add(new Customer() { Address = "Torikatu 38", City = "Oulu", CompanyName = "Wartian Herkku", ContactName = "Pirkko Koskitalo", ContactTitle = "Accounting Manager", Country = "Finland", Phone = "981-443655", PostalCode = "90110", Region = "", Amount = 718 });
            list.Add(new Customer() { Address = "Rua do Mercado, 12", City = "Resende", CompanyName = "Wellington Importadora", ContactName = "Paula Parente", ContactTitle = "Sales Manager", Country = "Brazil", Phone = "(14) 555-8122", PostalCode = "08737-363", Region = "SP", Amount = 372 });
            list.Add(new Customer() { Address = "305 - 14th Ave. S. Suite 3B", City = "Seattle", CompanyName = "White Clover Markets", ContactName = "Karl Jablonski", ContactTitle = "Owner", Country = "USA", Phone = "(206) 555-4112", PostalCode = "98128", Region = "WA", Amount = 397 });
            list.Add(new Customer() { Address = "Keskuskatu 45", City = "Helsinki", CompanyName = "Wilman Kala", ContactName = "Matti Karttunen", ContactTitle = "Owner/Marketing Assistant", Country = "Finland", Phone = "90-224 8858", PostalCode = "21240", Region = "", Amount = 734 });
            list.Add(new Customer() { Address = "ul. Filtrowa 68", City = "Warszawa", CompanyName = "Wolski Zajazd", ContactName = "Zbyszek Piestrzeniewicz", ContactTitle = "Owner", Country = "Poland", Phone = "(26) 642-7012", PostalCode = "01-012", Region = "", Amount = 889, IsActive = false });
            dataGrid1.FilteredItemsSource = list;
        }
    }
}
